import {fail,pinHash,sha,deviceProof,adminAllowed} from './security.mjs';
import {bounds,range,totals,duration,localDate,csvCell} from './time.mjs';
export class Service{
 /** @param {any} db @param {any} env @param {any} user */
 constructor(db,env,user=null){this.db=db;this.env=env;this.user=user}
 stmt(sql,...args){return this.db.prepare(sql).bind(...args)}
 async approveBrowser(req,name){
  this.admin();
  if(this.env.BROWSER_CLOCKING!=='true'||new URL(req.url).protocol!=='https:')fail(403,'Browser approval requires enabled HTTPS hosting.');
  const token=Date.now()+'.'+crypto.randomUUID()+crypto.randomUUID();
  await this.deviceEdit({fingerprint:await sha('browser:'+token),name,active:true});
  return `ph_browser=${token}; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=31536000`;
 }
 async device(req,body){
  if(this.env.BROWSER_CLOCKING==='true'){
   const token=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('ph_browser='))?.slice(11)||'';
   const issued=Number(token.split('.')[0]),now=Date.now();
   if(new URL(req.url).protocol!=='https:'||!/^\d{13}\.[a-f0-9-]{72}$/.test(token)||issued>now||now-issued>=31536000000)fail(403,'This browser is not approved. Ask an admin to approve it under Clocking access.');
   const d=await this.stmt('SELECT * FROM devices WHERE fingerprint=? AND active=1',await sha('browser:'+token)).first();
   if(!d)fail(403,'This browser is not approved, or its access has been revoked.');
   return {...d,mode:'browser'};
  }
 if(this.env.LOCAL_CLOCKING===true && ['127.0.0.1','localhost','[::1]'].includes(new URL(req.url).hostname))return {fingerprint:'local-laptop',name:'Local laptop',mode:'local'};const proof=await deviceProof(req,body,this.env.DEVICE_GATEWAY_SECRET);const d=await this.stmt('SELECT * FROM devices WHERE fingerprint=? AND active=1',proof.fingerprint).first();if(!d)fail(403,'This Mac is not approved, or its certificate has been revoked.');try{await this.db.batch([this.stmt('DELETE FROM nonces WHERE expires < ?',Date.now()),this.stmt('INSERT INTO nonces VALUES (?,?)',proof.nonce,proof.expires)])}catch{fail(403,'Device proof has already been used. Please try again.')}return d;}
 admin(){if(!adminAllowed(this.user,this.env.ADMIN_USER_IDS))fail(403,'Administrator access required. Sign in with the admin password.');return this.user.userId}
 async limit(key,max=5){const now=Date.now();const row=await this.stmt('INSERT INTO attempts(key,count,until) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN attempts.until<=? THEN 1 ELSE attempts.count+1 END, until=CASE WHEN attempts.until<=? THEN excluded.until ELSE attempts.until END RETURNING count,until',key,now+900000,now,now).first();if(row.count>max)fail(429,'Too many attempts. Please wait 15 minutes before trying again.');}
 async session(req,device){const cookie=req.headers.get('cookie')||'';const token=cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('ph_session='))?.slice(11);if(!token)fail(401,'Enter your code again.');const tokenHash=await sha(token);const s=await this.stmt('SELECT s.*,e.name FROM sessions s JOIN engineers e ON e.id=s.engineer_id WHERE token_hash=? AND device=? AND expires>? AND e.active=1',tokenHash,device.fingerprint,Date.now()).first();if(!s)fail(401,'Your session expired. Enter your code again.');return s}
 async clock(req,path,body,raw){const device=await this.device(req,raw);
 if(path==='verify'){await this.limit('device:'+device.fingerprint);const hash=await pinHash(body.pin,this.env.PIN_PEPPER);const e=await this.stmt('SELECT id,name FROM engineers WHERE pin_hash=? AND active=1',hash).first();if(!e)fail(401,'That code wasn’t recognised. Please try again.');await this.stmt('UPDATE attempts SET count=MAX(0,count-1) WHERE key=?','device:'+device.fingerprint).run();const shift=await this.stmt('SELECT id,started_at FROM shifts WHERE engineer_id=? AND ended_at IS NULL',e.id).first();const token=crypto.randomUUID()+crypto.randomUUID();await this.db.batch([this.stmt('DELETE FROM sessions WHERE expires<?',Date.now()),this.stmt('INSERT INTO sessions VALUES (?,?,?,?)',await sha(token),e.id,device.fingerprint,Date.now()+45000)]);return{data:{name:e.name,shiftId:shift?.id||null,startedAt:shift?.started_at||null},token};}
 const s=await this.session(req,device);const now=Date.now();let shift;
 if(path==='in'){const id=crypto.randomUUID();try{const result=await this.db.batch([this.stmt('INSERT INTO shifts(id,engineer_id,started_at,device) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM sessions WHERE token_hash=? AND expires>?) RETURNING id',id,s.engineer_id,now,device.fingerprint,s.token_hash,now),this.stmt('DELETE FROM sessions WHERE token_hash=?',s.token_hash)]);if(result[0].results?.length!==1)fail(409,'Session already used. Enter your code to check your status.');shift=id;}catch(e){if(e.status)throw e;fail(409,'Already clocked in, or this shift overlaps an existing entry. Enter your code to check your status.')}}
 else if(path==='out'){const result=await this.db.batch([this.stmt('UPDATE shifts SET ended_at=?,version=version+1 WHERE id=? AND engineer_id=? AND ended_at IS NULL AND EXISTS(SELECT 1 FROM sessions WHERE token_hash=? AND expires>?)',now,body.shiftId||'',s.engineer_id,s.token_hash,now),this.stmt("INSERT INTO audit(entity,entity_id,actor,at,reason,before,after) SELECT 'shift',id,?,?, 'Clock out',NULL,CAST(json_object('id',id,'engineer_id',engineer_id,'started_at',started_at,'ended_at',ended_at,'device',device,'version',version) AS TEXT) FROM shifts WHERE id=? AND engineer_id=? AND ended_at=? AND EXISTS(SELECT 1 FROM sessions WHERE token_hash=? AND expires>?)",'engineer:'+s.engineer_id,now,body.shiftId||'',s.engineer_id,now,s.token_hash,now),this.stmt('DELETE FROM sessions WHERE token_hash=?',s.token_hash)]);if(result[0].meta.changes!==1)fail(409,'This shift has changed or was already closed. Enter your code to check your status.');shift=body.shiftId;}
 else fail(404,'Unknown action.');return{data:{name:s.name,action:path,at:now,shiftId:shift},clear:true};
 }
 async report(query){this.admin();const now=Date.now(),b=bounds(now);let r;try{r=range(query.get('from')||b.today,query.get('to')||b.today)}catch(e){fail(400,e.message)}const engineer=query.get('engineer')||'';const all=(await this.stmt('SELECT s.*,e.name FROM shifts s JOIN engineers e ON e.id=s.engineer_id WHERE (?=\'\' OR e.id=?) ORDER BY s.started_at DESC',engineer,engineer).all()).results;const engineers=(await this.stmt('SELECT id,name,active FROM engineers ORDER BY name').all()).results;const selected=all.filter(s=>s.started_at<r.end&&(s.ended_at??now)>r.start).map(s=>({...s,rangeMs:duration(s,r.start,r.end,now),missing:s.ended_at===null&&now-s.started_at>16*3600000}));return{browserClocking:this.env.BROWSER_CLOCKING==='true',now,from:query.get('from')||b.today,to:query.get('to')||b.today,engineers,shifts:selected,current:all.filter(s=>s.ended_at===null),today:totals(all,...Object.values(range(b.today,b.today)),now),week:totals(all,...Object.values(range(b.week,b.today)),now),selected:totals(all,r.start,r.end,now),devices:(await this.stmt('SELECT * FROM devices ORDER BY name').all()).results};}
 async editEngineer(body){const actor=this.admin();const name=String(body.name||'').trim();if(!name||name.length>100)fail(400,'Enter a name, up to 100 characters.');if(typeof body.active!=='boolean')fail(400,'Choose an active status.');const id=body.id||crypto.randomUUID();const old=await this.stmt('SELECT * FROM engineers WHERE id=?',id).first();if(body.id&&!old)fail(404,'Engineer not found.');const hash=body.pin?await pinHash(body.pin,this.env.PIN_PEPPER):old?.pin_hash;if(!hash)fail(400,'Enter a unique six-digit PIN.');const before=old?JSON.stringify({name:old.name,active:old.active}):null;try{await this.db.batch([this.stmt('INSERT INTO engineers(id,name,pin_hash,active) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,pin_hash=excluded.pin_hash,active=excluded.active',id,name,hash,body.active?1:0),this.stmt('DELETE FROM sessions WHERE engineer_id=?',id),this.stmt('INSERT INTO audit(entity,entity_id,actor,at,reason,before,after) VALUES(?,?,?,?,?,?,?)','engineer',id,actor,Date.now(),old?'Engineer updated'+(body.pin?'; PIN reset':''):'Engineer created',before,JSON.stringify({name,active:body.active,pinReset:!!body.pin}))]);}catch{fail(409,'That PIN is already assigned. Choose a different code.')}return{ok:true};}
 async correct(body){const actor=this.admin();const reason=String(body.reason||'').trim();if(reason.length<3||reason.length>1000)fail(400,'A correction reason (3–1,000 characters) is required.');const start=Date.parse(body.start),end=body.end?Date.parse(body.end):null;const hasZone=v=>/T.*(Z|[+-]\d{2}:\d{2})$/.test(v||'');if(!hasZone(body.start)||(body.end&&!hasZone(body.end))||!Number.isFinite(start)||(end!==null&&!Number.isFinite(end))||start>Date.now()||(end!==null&&(end<=start||end>Date.now())))fail(400,'Use valid ISO timestamps with Z or a timezone offset. End must follow start; future times are not allowed.');const old=await this.stmt('SELECT * FROM shifts WHERE id=?',body.id).first();if(!old)fail(404,'Shift not found.');if(old.version!==body.version)fail(409,'This entry changed. Refresh before correcting it.');const after={...old,started_at:start,ended_at:end,version:old.version+1};try{await this.db.batch([this.stmt('INSERT INTO audit(entity,entity_id,actor,at,reason,before,after) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM shifts WHERE id=? AND version=?)','shift',old.id,actor,Date.now(),reason,JSON.stringify(old),JSON.stringify(after),old.id,old.version),this.stmt('UPDATE shifts SET started_at=?,ended_at=?,version=version+1 WHERE id=? AND version=?',start,end,old.id,old.version)]).then(r=>{if(r[1].meta.changes!==1)fail(409,'Entry changed. Refresh and try again.')})}catch(e){if(e.status)throw e;fail(409,'This correction overlaps another shift. Check the times.')}return{ok:true};}
 async deviceEdit(body){const actor=this.admin();if(!/^[a-f0-9]{64}$/.test(body.fingerprint||'')||!String(body.name||'').trim()||String(body.name).length>100||typeof body.active!=='boolean')fail(400,'Enter a device name, a lowercase SHA-256 fingerprint (64 characters), and an active status.');const old=await this.stmt('SELECT * FROM devices WHERE fingerprint=?',body.fingerprint).first();await this.db.batch([this.stmt('INSERT INTO devices VALUES(?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET name=excluded.name,active=excluded.active',body.fingerprint,body.name,body.active?1:0),this.stmt('DELETE FROM sessions WHERE device=?',body.fingerprint),this.stmt('INSERT INTO audit(entity,entity_id,actor,at,reason,before,after) VALUES(?,?,?,?,?,?,?)','device',body.fingerprint,actor,Date.now(),'Device approval updated',old?JSON.stringify(old):null,JSON.stringify(body))]);return{ok:true};}
 async history(id){this.admin();return (await this.stmt('SELECT * FROM audit WHERE entity_id=? ORDER BY id DESC',id).all()).results;}
 async export(query){const r=await this.report(query);const fmt=ms=>ms===null?'':new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',dateStyle:'short',timeStyle:'long'}).format(ms);return[['Name','Date (London)','Clock in (London)','Clock out (London)','Status','Total shift hours','Exact shift seconds','Seconds in selected range','Clock in UTC','Clock out UTC'],...r.shifts.map(s=>[s.name,localDate(s.started_at),fmt(s.started_at),fmt(s.ended_at),s.missing?'Missing clock-out (over 16h)':s.ended_at===null?'Open / ongoing':'Completed',((s.ended_at??r.now)-s.started_at)/3600000,((s.ended_at??r.now)-s.started_at)/1000,s.rangeMs/1000,new Date(s.started_at).toISOString(),s.ended_at===null?'':new Date(s.ended_at).toISOString()])].map(row=>row.map(csvCell).join(',')).join('\r\n');}
}
